[package]
name = "sgx-dcap-quote-verifier-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
sgx-dcap-quote-verifier = { path = "../sgx-dcap-quote-verifier" }
